### ISSUE TITLE
Help with auto catcher

### ISSUE THREAD

**Issue by GoldenBlaster** [joker-ware/JokerCord#30]
Due to some certain circumstances I am not able to access the website, so I just decided to review the code and change the “preferences.json” myself. I was able to get my client login and working and all, it even was able to spam and change messages, but the only thing I couldn’t figure out on was how to enable/disable the servers/guilds for which it should catch the pokes. I tried going over to the “User” file and looked over “guilds.json” but wasn’t able to make sense on how to enable the servers and the auto catch overall. Can you please tell how could I do that? Thanks in advance :)

**Comment by joker-ware** [comment]
I don't know why this happens, for some reason some people are having problems while writing to Json files in Windows, it might be a permissions problem but I don't know as I don't use Windows myself. Users.json should be auto filled every time you start the bot. Please tell me whether it works if you run the program as administrator. I can't currently provide you with an example of user.json because I am not at home, and will not be until tomorrow.

**Comment by GoldenBlaster** [comment]
Actually I figured out what should be entered in the “guilds.json” file, and everything’s working alright . Also I was using my iPad to host the catcher, so I didn’t try out running the program as administrator. Thanks anyways :)
